# Generated by Django 6.0.7 on 2026-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=200)),
                ('author', models.CharField(help_text="Enter the author's name", max_length=200)),
                ('genre', models.CharField(help_text="Enter the book's genre", max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Old', 'Old')], default='Good', help_text='Select the condition of the book', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the book', max_digits=10)),
                ('description', models.TextField(help_text='Provide a description of the book')),
                ('owner_name', models.CharField(help_text='Enter your name (owner)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
